'''
``<prefix>_variable_mapping.csv``: every variable and parameter of a model with the LaTeX
symbol it is written as in generated methods (``methods.py``).

Columns:

* ``variable_name`` -- CA's canonical name, ``component/variable`` with ``_module`` stripped
  from the component (``mod_C/z``, ``parameters/p_mod_A``): the names obs_data operands,
  params_for_id and CUFLynx use;
* ``latex`` -- the symbol, without ``$``. Generated by the rule in ``latex_names.py``; edit
  freely. Regenerating keeps every row's ``latex`` that is already in the file;
* ``kind`` -- ``state``, ``parameter`` (in ``parameters`` / ``parameters_global``),
  ``constant`` (a literal defined in a module), ``algebraic`` or ``time``;
* ``component`` -- the model component it is defined in;
* ``units``.

Only CellML models are read (through Myokit's importer, which resolves imports and merges
connected variables -- so a module input connected to another module's output is not a row
of its own: the equations use the output's symbol).
'''

import csv
import os
import warnings

from libcuflynx.reporting.latex_names import module_subscript, symbol

COLUMNS = ('variable_name', 'latex', 'kind', 'component', 'units')
PARAMETER_COMPONENTS = ('parameters', 'parameters_global')
ENVIRONMENT = 'environment'
MODULE_SUFFIX = '_module'
# the single vessel-array record a module (or supermodule) is generated alone as; see
# calibration_workflow/naming.py
STANDALONE_VESSEL = 'mod'


class VariableMappingError(ValueError):
    '''A model or mapping file that cannot be read.'''


def load_model(model_path):
    '''The CellML model at ``model_path`` as a Myokit model (imports resolved).'''
    if not str(model_path).lower().endswith('.cellml'):
        raise VariableMappingError(
            f'{model_path}: only CellML models can be mapped and written as equations '
            f'(generate the model with model_type cellml).')
    import myokit.formats.cellml as cellml
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        try:
            return cellml.CellMLImporter().model(str(model_path))
        except Exception as exc:  # Myokit raises its own import errors
            raise VariableMappingError(f'{model_path}: cannot read the model: {exc}') from exc


def strip_module(component_name):
    if component_name.endswith(MODULE_SUFFIX) and len(component_name) > len(MODULE_SUFFIX):
        return component_name[:-len(MODULE_SUFFIX)]
    return component_name


def canonical_name(variable):
    '''``component/variable`` for a Myokit variable.'''
    return f'{strip_module(variable.parent().name())}/{variable.name()}'


def is_time(variable):
    return variable.binding() == 'time'


def variable_kind(variable):
    if is_time(variable):
        return 'time'
    if variable.is_state():
        return 'state'
    component = variable.parent().name()
    rhs = variable.rhs()
    literal = rhs is not None and rhs.is_literal()
    if component in PARAMETER_COMPONENTS:
        return 'parameter'
    return 'constant' if literal else 'algebraic'


def module_components(model):
    '''The components that are modules (not parameters, globals or the environment), in
    model order. Components without variables are left out: the generator adds empty
    connection components (``sum_blood_volume``, ``global`` ...) whatever the model.'''
    return [c for c in model.components()
            if c.name() not in PARAMETER_COMPONENTS and c.name() != ENVIRONMENT
            and c.count_variables() > 0]


def _module_names(model):
    return {strip_module(c.name()) for c in module_components(model)}


def module_display_names(model):
    '''``{module name: name to show}``. A model whose modules were all generated as the
    standalone vessel ``mod`` (``mod``, ``mod_A`` ...) shows them without that prefix.'''
    names = _module_names(model)
    standalone = names and all(n == STANDALONE_VESSEL or n.startswith(STANDALONE_VESSEL + '_')
                               for n in names)
    shown = {}
    for name in names:
        if standalone:
            shown[name] = '' if name == STANDALONE_VESSEL else name[len(STANDALONE_VESSEL) + 1:]
        else:
            shown[name] = name
    return shown


def _split_parameter(name, modules):
    '''``p_mod_A`` -> ``('p', 'mod_A')`` when ``mod_A`` is a module; ``(name, None)`` else.'''
    for module in sorted(modules, key=len, reverse=True):
        suffix = '_' + module
        if name.endswith(suffix) and len(name) > len(suffix):
            return name[:-len(suffix)], module
    return name, None


def default_latex(variable, display=None):
    '''The default LaTeX symbol of a Myokit variable of a CA model.'''
    if is_time(variable):
        return 't'
    display = display if display is not None else module_display_names(variable.model())
    component = variable.parent().name()
    name = variable.name()
    if component == 'parameters_global':
        return symbol(name)
    if component == 'parameters':
        base, module = _split_parameter(name, display)
        if module is None:
            return symbol(name)
        shown = display[module]
        return symbol(base, [module_subscript(shown)] if shown else [])
    shown = display.get(strip_module(component), strip_module(component))
    return symbol(name, [module_subscript(shown)] if shown else [])


def _units(variable):
    unit = variable.unit()
    if unit is None:
        return ''
    text = str(unit)
    text = text[1:-1] if text.startswith('[') and text.endswith(']') else text
    return 'dimensionless' if text == '1' else text


def default_variable_mapping(model):
    '''Rows (dicts with COLUMNS) for every variable of ``model`` (a path or Myokit model):
    the environment's time, then globals, parameters, then each module's states, constants
    and algebraic variables.'''
    if not hasattr(model, 'components'):
        model = load_model(model)
    display = module_display_names(model)
    order = {'time': 0, 'state': 1, 'constant': 2, 'algebraic': 3, 'parameter': 1}
    rows = []
    components = ([c for c in model.components() if c.name() == ENVIRONMENT]
                  + [model.get(n) for n in ('parameters_global', 'parameters')
                     if model.has_component(n)]
                  + module_components(model))
    for component in components:
        variables = sorted(component.variables(deep=True),
                           key=lambda v: order.get(variable_kind(v), 9))
        for variable in variables:
            kind = variable_kind(variable)
            if component.name() == ENVIRONMENT and kind != 'time':
                continue
            rows.append({'variable_name': canonical_name(variable),
                         'latex': default_latex(variable, display), 'kind': kind,
                         'component': component.name(), 'units': _units(variable)})
    return rows


def read_variable_mapping(path):
    '''``{variable_name: row}`` from a mapping CSV.'''
    with open(path, newline='', encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)
        missing = [c for c in ('variable_name', 'latex') if c not in (reader.fieldnames or [])]
        if missing:
            raise VariableMappingError(f'{path}: a variable mapping needs the columns '
                                       f'{list(COLUMNS)}; {missing} missing.')
        rows = {}
        for row in reader:
            name = (row.get('variable_name') or '').strip()
            if name:
                rows[name] = {c: (row.get(c) or '').strip() for c in COLUMNS}
    return rows


def variable_mapping(model, existing=None):
    '''The model's rows, with the ``latex`` of every row already in ``existing`` (a path or a
    ``{variable_name: row}`` dict) kept. Each row gets ``edited``: whether its latex differs
    from the default rule.'''
    rows = default_variable_mapping(model)
    if isinstance(existing, (str, os.PathLike)):
        existing = read_variable_mapping(existing) if os.path.isfile(existing) else {}
    existing = existing or {}
    for row in rows:
        default = row['latex']
        kept = (existing.get(row['variable_name']) or {}).get('latex')
        if kept:
            row['latex'] = kept
        row['default_latex'] = default
        row['edited'] = row['latex'] != default
    return rows


def write_variable_mapping(rows, path):
    '''Write mapping ``rows`` (dicts with at least variable_name and latex) as a CSV.'''
    seen = set()
    for row in rows:
        name = (row.get('variable_name') or '').strip()
        if not name:
            raise VariableMappingError('a mapping row has no variable_name.')
        if name in seen:
            raise VariableMappingError(f'"{name}" is in the mapping twice.')
        seen.add(name)
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    tmp = str(path) + '.tmp'
    with open(tmp, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=list(COLUMNS), extrasaction='ignore')
        writer.writeheader()
        for row in rows:
            writer.writerow({c: row.get(c, '') for c in COLUMNS})
    os.replace(tmp, path)
    return str(path)


def update_variable_mapping_file(model, path):
    '''Create or refresh the mapping file at ``path`` for ``model``: new variables get the
    default symbol, existing rows keep theirs, rows for variables the model no longer has
    are dropped. Returns the rows.'''
    rows = variable_mapping(model, path)
    write_variable_mapping(rows, path)
    return rows


def check_variable_mapping(rows):
    '''Problems a reader would notice: ``{'empty': [names], 'duplicates': {latex: [names]}}``
    -- two variables written with the same symbol cannot be told apart in the equations.'''
    by_latex = {}
    empty = []
    for row in rows:
        latex = (row.get('latex') or '').strip()
        if not latex:
            empty.append(row['variable_name'])
        else:
            by_latex.setdefault(latex, []).append(row['variable_name'])
    return {'empty': empty,
            'duplicates': {k: v for k, v in by_latex.items() if len(v) > 1}}


def default_mapping_path(model_path, file_prefix=None):
    '''``<model dir>/<prefix>_variable_mapping.csv``, the prefix being the model's stem with a
    trailing ``_flat`` dropped.'''
    stem = file_prefix or os.path.splitext(os.path.basename(str(model_path)))[0]
    if stem.endswith('_flat'):
        stem = stem[:-len('_flat')]
    return os.path.join(os.path.dirname(os.path.abspath(str(model_path))),
                        f'{stem}_variable_mapping.csv')
